# Generated by Django 5.0.6 on 2024-06-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maindb',
            options={'verbose_name': 'Ishtirokchi', 'verbose_name_plural': 'Ishtirokchilar'},
        ),
        migrations.RenameField(
            model_name='maindb',
            old_name='name',
            new_name='name1',
        ),
        migrations.AddField(
            model_name='maindb',
            name='name2',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
    ]
